### PR TITLE
WebSearch: fix pagination when ranking

### PR DESCRIPTION
**Pull request by tsgit**
* sorting results by citations is properly sliced
      via rg and jrec

Signed-off-by: Thorsten Schwander <thorsten.schwander@gmail.com>

### CODE REVIEW

**Comment by tsgit** [comment]
@kaplun  this fixes the pagination bug for me with rm=citation

`sort_records()`   -- aka bibsort returns slices, 

https://github.com/inspirehep/invenio/blob/prod/modules/websearch/lib/search_engine.py#L4245
and
https://github.com/inspirehep/invenio/blob/prod/modules/websearch/lib/search_engine.py#L4257

however

`rank_by_citation()` returns full sorted list via `rank_records()`

https://github.com/inspirehep/invenio/blob/prod/modules/websearch/lib/search_engine.py#L4199

**Comment by kaplun** [comment]
LGTM :+1:

**Comment by kaplun** [comment]
What I don't understand though is why is not there in Invenio 1. Have this been fixed there?

**Comment by tsgit** [comment]
mmh, to  me it looks like maint-1.2 should show the same issue when ranking search results by citation count, but I don't have a test instance up

**Pull request merged**
