### PR TITLE
BibAuthorID: Fix of wrong current institution

### PR DESCRIPTION
**Pull request by MSusik**
Signed-off-by: Mateusz Susik mateusz.susik@cern.ch

Fixes also indentation in template file.

### CODE REVIEW

**Comment by glouppe** [comment]
Looks good to me. +1 for merge

**Comment by jalavik** [comment]
Code-wise it looks fine to me as well, although I am not fully aware of the context (as you can see below from my makeshift log message example). Just some minor cosmetics:
- Can you update the commit log message with bullet points of the changes and lower case subject after module name (to follow [Invenio guidelines](http://invenio.readthedocs.org/en/latest/developers/git-workflow.html#r2-remarks-on-commit-log-messages) ). For example:

```
BibAuthorID: current institution fix

* Fixes the problem in XXXX where the wrong institution was not handled by YYY.
* Improves indentation in templates.

Signed-off-by: Mateusz Susik mateusz.susik@cern.ch
```

While updating it you can then also add `Reviewed-by:` for @glouppe  and myself.
- Note that in the next version of Invenio, there will be guidelines on indentation in templates to keep a consistent 2 or 4 spaced indentation per file.

**Comment by jalavik** [comment]
One more thing. More tests seems to be failing with this update. @MSusik  can you have a look at the Travis output to see if it is relevant to your changes?

Note that `prod` fails with some tests, so some failures (websearch) you can "ignore" as they will be fixed by us ASAP. [`prod` travis output](https://travis-ci.org/inspirehep/invenio/builds/36266105)

**Comment by glouppe** [comment]
(@MSusik is unavailable today, so this will have to wait until Monday.)

**Comment by jalavik** [comment]
Merged as 9fe299d

**Pull request closed without merging**
