### PR TITLE
BibIndex: fix authorcount for data records

### PR DESCRIPTION
**Pull request by tsgit**
Signed-off-by: Thorsten Schwander thorsten.schwander@gmail.com

### CODE REVIEW

**Comment by tsgit** [comment]
it's a hack, but maybe a better check would be to look at collection 

`001401980 980__ $$aDATA`

and not mix this with other records without authors. There's 15k records in HEP with authorcount == 0
https://inspirehep.net/search?p=authorcount%3A0

or plainly

https://inspirehep.net/search?p=authorcount%3A0&of=tx&ot=100,700,110&rg=1000

**Comment by tsgit** [comment]
mmh, more complexity

termlist might be empty because of deletion. from the bibindex verbose log:

2016-08-30 03:47:28 --> ... record 1405225 was declared deleted, removing its word list
2016-08-30 03:47:28 --> ... record 1405225, termlist: []

so the patch needs to be amended to deal with empty list or face an IndexError

damn quick hacks and no tests

**Comment by kaplun** [comment]
@tsgit I remember in the past we have decided to drop the automatic refreshing of records inheriting authors (such as Data) and force it by hand on a bi-weekly basis. However `authorcount` was not taken into account.

I have just scheduled a bi-weekly `authorcount` for `Data` that should simply force computing the numbers.

Maybe this is all that is needed :+1:

**Comment by kaplun** [comment]
@tsgit nevermind what I said. Your patch is correct. Authorcount would indeed have always returned at least one term, thus not entering in the `if`. WRT checking if it is Data, this is not necessary, because this is what is actually done in the body of the `if`, i.e. to check if the record has a parent record from which to borrow author information.

**Pull request merged**
