### PR TITLE
BibauthorID: error message when merging of profiles fails

### PR DESCRIPTION
**Pull request by atsikiridis**
- A message is shown when trying to merge an author profile to a
  coauthor. This merging should not be possible.

Signed-off-by: Artem Tsikiridis artem.tsikiridis@cern.ch

### CODE REVIEW

**Comment by atsikiridis** [comment]
cc @glouppe

**Comment by kaplun** [comment]
What is this bug about? What does it mean to merge an author profile with a co-author?

**Comment by glouppe** [comment]
@kaplun For good reasons, you should not be able to merge two profiles that share a same publication. In production, this is already not possible, but no meaningful error message is shown. This PR adds one :)

**Comment by atsikiridis** [comment]
@glouppe @kaplun I made it more general for all the cases that the merging should fail. There was already a function called  `merge_is_allowed` but it was ignored. Basically, in this PR we add the case of the coauthor and then we use the function to display the message.

**Comment by glouppe** [comment]
This is good for me to go. +1 for merge.

**Pull request merged**
