### PR TITLE
installation: pin invenio-records

### PR DESCRIPTION
**Pull request by kaplun**
- Pins invenio-records to not include invenio_base yet.

Signed-off-by: Samuele Kaplun samuele.kaplun@cern.ch

### CODE REVIEW

**Comment by kaplun** [comment]
@jalavik here it is

**Comment by jalavik** [comment]
@kaplun  Ah, you meant in Invenio. It's pinned on the overlay already so strange that it would appear: https://github.com/inspirehep/inspire-next/blob/master/setup.py#L52

**Comment by kaplun** [comment]
Ah maybe due to the fact I was testing for `invenio-base` right after installing `invenio`. Which would make sense right? I install `invenio`, which would have triggered `invenio-records==0.3.3`. This brings in `invenio-base`. Then if I were installing `inspire-next` it would have downgraded `invenio-records` to `0.3.2`, but would have left `invenio-base`.

**Comment by jalavik** [comment]
Yeah, @Panos512 had a similar problem, and so uninstalling `invenio-records`, then installing hard `invenio-records==0.3.2` as well as removing `invenio-base`, then install inspire worked. Anyway, we could pin this one here, but we would have to pin the others as well probably.

**Comment by kaplun** [comment]
I think this is nowadays superseded.

**Pull request closed without merging**
