### PR TITLE
Use rename_subfield_filter in rename_subfield

### PR DESCRIPTION
**Pull request by michamos**

### CODE REVIEW

**Comment by michamos** [comment]
@kaplun can you deploy this, as well as inspirehep/inspire#269 to test when it's alive again?

**Comment by kaplun** [comment]
I think you took a strange branch. Can you rebase it on top of latest prod and push again?

**Comment by michamos** [comment]
@kaplun after some git magic I managed to simplify the history

**Comment by michamos** [comment]
@kaplun: the last commit has been run successfully on test

**Pull request merged**
