### PR TITLE
BibIndex: new country tokenizer, country index, country KB

### PR DESCRIPTION
**Pull request by fpoli**
- Amends SPIRES to Invenio converter to use index cc->country
- Disables SPIRES sintax conversion cc->postalcode
- Adds BibIndexCountryTokenizer
- Adds regression tests for country tokenization on country index
- Adds countrynames-to-country.kb
- Adds country index and country field (in tabfill and with an upgrade script)
- Adds command line utility 'kbload', useful to load a new kb from file
- Automatically loads 'countrycode-to-country.kb' when installing demo site
- Adds configuration variable CFG_WEBSEARCH_INSTITUTION_COLLECTIONS
- Adds tags 110__u, 371__d, 371__g, 371__x
- Assumes that the country of the institution records does not change.
  If it changes, a manual full reindexing is required.

Conflicts:
    modules/bibindex/lib/bibindex_engine.py
    modules/bibindex/lib/bibindex_regression_tests.py
    modules/miscutil/sql/tabcreate.sql
    modules/miscutil/sql/tabdrop.sql
    modules/miscutil/sql/tabfill.sql

Signed-off-by: Federico Poli federico.poli@cern.ch

### CODE REVIEW

**Comment by kaplun** [comment]
@fpoli you have also made a pull request on official Invenio for this one? Otherwise I'd like to make some inline comments...

**Comment by jalavik** [comment]
As soon as new-prod is out, I guess we can rebase this branch on that. Then a pull request on master @ inveniosoftware can be made as well.

**Comment by fpoli** [comment]
@kaplun, not yet. I was waiting here for review before creating a pull request. I have a branch on master but it is not up to date, the rebase will need some work since BibIndex changed.

**Comment by Osso** [comment]
deployed

**Pull request closed without merging**
