### PR TITLE
textutils: further escape '>' in XML

### PR DESCRIPTION
**Pull request by kaplun**
Signed-off-by: Samuele Kaplun samuele.kaplun@cern.ch

### CODE REVIEW

**Comment by kaplun** [comment]
@tsgit this should fix the error @annetteholtkamp is seeing when trying to BibEdit the record https://inspirehep.net/record/1331745/export/xm which has a non escape `]]>` character sequence that bombs some parsers.

@tsgit can you deploy if you think it's correct? I have to go now. 

The corresponding record(s?) that Annette was trying to edit need to be fixed by hand by reuploading MARCXML via bibupload.

**Comment by kaplun** [comment]
cc: @jacquerie

**Comment by tsgit** [comment]
ah, this is interesting. technically the `>` doesn't have to be escaped in XML, only the opening `<` , but parsers fail on closing CDATA `]]>`
I'll deploy today.

**Comment by tsgit** [comment]
@kaplun I deployed the patch, but bibupload (task 78884) fails because of the existing bad record -- bibupload_revisionverifier can't parse the existing record. I'll have to get creative I guess.

**Comment by kaplun** [comment]
I guess you just need to replace by hand the `xm` format in `bibfmt` table. The other format and table are unrelated to XML. Note that the value in bibfmt is compressed with zlib.

**Comment by tsgit** [comment]
oh, I would never do something as nefarious as that, bypassing all checks :stuck_out_tongue_winking_eye: 

I note the problem with this record goes back to July 2015 and I find a few associated exceptions over the past year. About time something is finally done, so I ran the below earlier:

```
$ cat fix-xml-rec.py 
from invenio.search_engine import zlib
from invenio.dbquery import run_sql
x = run_sql('select value from bibfmt where id_bibrec=1331745 and format="xm"')
xm = zlib.decompress(x[0][0])
nxm = xm.replace(']]>', ']]&gt;')
nxm = zlib.compress(nxm)
run_sql('update bibfmt set value=%s where id_bibrec=1331745 and format="xm"', (nxm,))
```

**Pull request merged**
