### PR TITLE
BibSched: do not send emergency on bibupload (OPS)

### PR DESCRIPTION
**Pull request by jalavik**
I got fed up and created this hack. cc @jmartinm @kaplun 

It's probably not perfect..

### CODE REVIEW

**Comment by jmartinm** [comment]
:+1:

**Comment by kaplun** [comment]
It's good enough :smile: Does it matches also bibupload:foo processes?

**Comment by jalavik** [comment]
@kaplun Probably not, I could change to just look for `"bibupload"`. I'll test later.

**Comment by kaplun** [comment]
Superseeded by #255

**Pull request closed without merging**
