### PR TITLE
config: make Labs hostname configurable

### PR DESCRIPTION
**Pull request by kaplun**
Signed-off-by: Samuele Kaplun <samuele.kaplun@cern.ch>

### CODE REVIEW

**Comment by kaplun** [comment]
cc: @david-caro

**Comment by kaplun** [comment]
OK Just tested with success on test. Also files are all passing Pylint :-)

**Comment by david-caro** [comment]
looks ok to me

**Comment by david-caro** [comment]
thanks :), I thought this was already merged and that the one I pointed out was a leftover...

**Pull request merged**
