### PR TITLE
BibAuthorID: Debug info no longer shown in Manage Pubs ticket box.

### PR DESCRIPTION
**Pull request by atsikiridis**
Signed-off-by: Artem Tsikiridis artem.tsikiridis@cern.ch

### CODE REVIEW

**Comment by atsikiridis** [comment]
cc @glouppe

**Comment by glouppe** [comment]
Nothing controversial in there. 

+1 for merge

**Comment by kaplun** [comment]
@atsikiridis can you make the commit log to respect the Invenio guidelines:
http://invenio-software.org/wiki/Tools/Git/Workflow#R2.Remarksoncommitlogmessages

In this way we can quickly include it upstream :smile:

**Comment by atsikiridis** [comment]
@kaplun you're right, sorry. Is it ok now ?

**Comment by jalavik** [comment]
Looks good. We can deploy and merge.

**Comment by kaplun** [comment]
Thanks, deployed

**Pull request merged**
