### PR TITLE
Orcidutils: pulling with orcid library

### PR DESCRIPTION
**Pull request by MSusik**
- Introduces new dependency - orcid
- Improves performance of orcid queries
- Uses API 2.0_rc1

Signed-off-by: Mateusz Susik mateusz.susik@cern.ch

### CODE REVIEW

**Comment by kaplun** [comment]
Any news from ORCID?

**Comment by kaplun** [comment]
Ping

**Comment by MSusik** [comment]
Ah, yes. They claim to have it fixed. Will check it on monday.

**Comment by MSusik** [comment]
Seems that it indeed works.

**Pull request merged**
