### PR TITLE
classification: serializable values in extra_data

### PR DESCRIPTION
**Pull request by Lilykos**
- Replaces KeywordToken instances, inside extra_data
  to a serializable format.

Signed-off-by: Ilias Koutsakis ilias.koutsakis@cern.ch

### CODE REVIEW

**Comment by kaplun** [comment]
Hi! Why is this against `inspirehep/invenio`? Shouldn't it be against `inveniosoftware/invenio-classifier`?

**Comment by jalavik** [comment]
@kaplun Yeah, if all goes well it will be part of `invenio-classifier`. It's for an upgrade script we need on production labs which runs on older version of Invenio without packages split.

**Comment by kaplun** [comment]
Right. I missed the `inspirehep:production` target branch hint. Thanks for explanation!

**Comment by jalavik** [comment]
Merged. Thanks!

**Pull request closed without merging**
